// Generated by CoffeeScript 1.3.3
(function() {
  var Client, Room;

  exports.io = require('socket.io');

  Client = require('./client').Client;

  Room = require('./room').Room;

  exports.setHost = function(host) {
    require('./httpcontroller').HTTPHost = host;
    return exports;
  };

  exports.listen = function(port) {
    var io;
    io = exports.io.listen(port);
    io.sockets.on('connection', function(socket) {
      return new Client(socket);
    });
    return exports;
  };

}).call(this);
