// Generated by CoffeeScript 1.3.3
(function() {
  var Client, Room;

  exports.io = require('socket.io');

  Client = require('./client').Client;

  Room = require('./room').Room;

  exports.setHost = function(host) {
    return require('./httpcontroller').HTTPHost = host;
  };

  exports.listen = function(port) {
    var io;
    io = exports.io.listen(port);
    return io.sockets.on('connection', function(socket) {
      return new Client(socket);
    });
  };

}).call(this);
