// Generated by CoffeeScript 1.3.3
(function() {
  var Room,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Room = require('./room').Room;

  exports.Client = (function() {

    function Client(socket, httpController) {
      this.socket = socket;
      this.httpController = httpController;
      this.ping = __bind(this.ping, this);

      this.joinRoom = __bind(this.joinRoom, this);

      this.disconnect = __bind(this.disconnect, this);

      this.broadcast = __bind(this.broadcast, this);

      this.socket.on('join', this.joinRoom);
      this.socket.on('send', this.broadcast);
      this.socket.on('disconnect', this.disconnect);
      this.socket.on('ping', this.ping);
    }

    Client.prototype.broadcast = function(obj) {
      var eventString, responseObject,
        _this = this;
      if (this.room == null) {
        return this.error("Not in room");
      }
      if (obj == null) {
        return this.error("Missing data");
      }
      responseObject = {};
      eventString = obj.event != null ? obj.event : "update";
      if (obj.broadcast != null) {
        responseObject.broadcast = obj.broadcast;
      }
      if (obj.backendRequest != null) {
        if (this.httpController == null) {
          return this.error("No backend server specified");
        }
        return this.httpController.request({
          data: obj.backendRequest.data,
          path: obj.backendRequest.path,
          method: obj.backendRequest.method,
          headers: obj.backendRequest.headers,
          error: function(error) {
            return console.error(error);
          },
          success: function(response) {
            responseObject.backendResponse = response;
            return _this.room.broadcast(eventString, responseObject);
          }
        });
      } else {
        return this.room.broadcast(eventString, responseObject);
      }
    };

    Client.prototype.disconnect = function() {
      var _ref;
      return (_ref = this.room) != null ? _ref.removeClient(this) : void 0;
    };

    Client.prototype.emit = function(message, data) {
      return this.socket.emit(message, data);
    };

    Client.prototype.error = function(errorMessage) {
      return this.socket.emit('error', errorMessage);
    };

    Client.prototype.joinRoom = function(data) {
      var _ref;
      if (!((data != null) && (data.userId != null) && (data.roomId != null))) {
        return;
      }
      if ((_ref = this.room) != null) {
        _ref.removeClient(this);
      }
      this.userId = data.userId;
      this.room = Room.get(data.roomId);
      return this.room.addClient(this);
    };

    Client.prototype.ping = function() {
      console.log('ping');
      return this.emit('pong');
    };

    return Client;

  })();

}).call(this);
