// Generated by CoffeeScript 1.3.3
(function() {

  exports.Room = (function() {

    Room.list = {};

    Room.get = function(roomId) {
      if (Room.list[roomId] == null) {
        Room.list[roomId] = new Room(roomId);
      }
      return Room.list[roomId];
    };

    function Room(id) {
      this.id = id;
      this.clients = [];
    }

    Room.prototype.addClient = function(client) {
      if (!(this.clients.indexOf(client) > -1)) {
        return this.clients.push(client);
      }
    };

    Room.prototype.removeClient = function(client) {
      var i, _ref;
      if ((i = this.clients.indexOf(client)) > -1) {
        [].splice.apply(this.clients, [i, i - i + 1].concat(_ref = [])), _ref;
      }
      if (this.clients.length === 0) {
        return delete Room.list[this.id];
      }
    };

    Room.prototype.broadcast = function(event, data) {
      var client, _i, _len, _ref, _results;
      _ref = this.clients;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        client = _ref[_i];
        _results.push(client.emit(event, data));
      }
      return _results;
    };

    return Room;

  })();

}).call(this);
