// Generated by CoffeeScript 1.3.3
(function() {
  var Connection, Room,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Room = require('./room');

  Connection = (function() {

    function Connection(socket, bronson, httpController) {
      this.socket = socket;
      this.bronson = bronson;
      this.httpController = httpController;
      this.ping = __bind(this.ping, this);

      this.joinRoom = __bind(this.joinRoom, this);

      this.disconnect = __bind(this.disconnect, this);

      this.broadcast = __bind(this.broadcast, this);

      this.socket.on('disconnect', this.disconnect);
      this.socket.on('join', this.joinRoom);
      this.socket.on('ping', this.ping);
      this.socket.on('send', this.broadcast);
    }

    Connection.prototype.broadcast = function(data) {
      var response, _ref,
        _this = this;
      if (this.room == null) {
        return this.error("Not in a room");
      }
      if (data == null) {
        return this.error("Missing data");
      }
      if (!data.event) {
        return this.error("No event name given");
      }
      if ((_ref = data.toSelf) == null) {
        data.toSelf = this.bronson.options.sendToSelf;
      }
      response = {};
      if (data.broadcast != null) {
        response.broadcast = data.broadcast;
      }
      if (!this.bronson.testing) {
        console.log("User '" + this.userId + "' broadcasts '" + data.event + "' into room '" + this.room.id + "'.");
      }
      if (data.backendRequest != null) {
        if (this.httpController == null) {
          return this.error("No backend server specified");
        }
        return this.httpController.request({
          data: data.backendRequest.data,
          path: data.backendRequest.path,
          method: data.backendRequest.method,
          headers: data.backendRequest.headers,
          error: function(error) {
            return console.error(error);
          },
          success: function(response) {
            response.backendResponse = response;
            return _this.room.broadcast(data.event, response, data.toSelf, _this);
          }
        });
      } else {
        return this.room.broadcast(data.event, response, data.toSelf, this);
      }
    };

    Connection.prototype.disconnect = function() {
      var _ref;
      if ((_ref = this.room) != null) {
        _ref.removeConnection(this);
      }
      return console.log("" + this.userId + " has disconnected");
    };

    Connection.prototype.emit = function(message, data) {
      return this.socket.emit(message, data);
    };

    Connection.prototype.error = function(errorMessage) {
      console.log("ERROR: " + errorMessage);
      return this.socket.emit('error', errorMessage);
    };

    Connection.prototype.joinRoom = function(data) {
      var _ref;
      if (!((data != null) && (data.userId != null) && (data.roomId != null))) {
        return;
      }
      if ((_ref = this.room) != null) {
        _ref.removeConnection(this);
      }
      this.userId = data.userId;
      this.room = Room.get(data.roomId);
      this.room.addConnection(this);
      console.log("" + data.userId + " has joined room " + data.roomId);
      return this.bronson.emit('room joined', data);
    };

    Connection.prototype.ping = function() {
      console.log('ping');
      return this.emit('pong');
    };

    return Connection;

  })();

  module.exports = Connection;

}).call(this);
